### PR TITLE
PassThroughEncoder Logging + other improvements

### LINKED ISSUE #208: PassThroughEncoder requires the introduction of Logging
Use the current logging library and method present in the ScalarEncoder as a "template" for the introduction of logging. This should include the corresponding unit test as well.

### PR DESCRIPTION
**Pull request by antidata**
Found this that can be helpful http://stackoverflow.com/questions/943367/string-format-with-lazy-evaluation/14078904#14078904

Fixes #208

### CODE REVIEW

**Comment by cogmission** [comment]
Please use the pattern below. The performance of the failure case is more important than the performance of the successful case. If "debug" is enabled, I don't care how long the method takes to complete because we are debugging or tracing or analyzing the code. If "debug" is **not** enabled, we want hotspot to remove the dead code altogether. With:  logger.debug("Logging in user " + user.getName() + " with id " + user.getId()); , this doesn't get to happen because the "debug" method will always be called - not only that, but they are using a non-"intern"ed String, which means that the actual String object is being created on every pass through this method (I mean the template portion before concatenating with the "other" arguments). We want to avoid creation of the String period.

Please let me know if this doesn't make sense to you, or you feel I have this wrong? 

if (logger.isDebugEnabled()) {     
  logger.debug("Logging in user " + user.getName() + " with id " + user.getId()); 
}

**Comment by cogmission** [comment]
@antidata Are you there?

**Comment by antidata** [comment]
@cogmission Hey, sorry for the delay, it was a hard week, I hope to have some time middle next week to complete this. Thanks!

**Comment by cogmission** [comment]
@antidata No problem at all. I just didn't know what was going on. Don't stress on it...

**Comment by antidata** [comment]
@cogmission I'm back!

agree with you, I'm trying to go further and looking for a way to avoid having `if (logger.isDebugEnabled())` across the codebase. So I came up with the following code in order to get a 'lazy evaluation':

`LOGGER.trace("closenessScores for expValues: {} and actValues: {} is: {}", LazyString.get((Void v) -> Arrays.toString(expectedInts)), actualInts, r);` this will evaluate `Arrays.toString(expectedInts)` only if trace is enabled.

you can check out LazyString [source code here](https://github.com/antidata/LazyEvaluationJava8/tree/master/src)

This is just a proposition, feel free to share your thoughts about it, if you know a better way to do it otherwise we can move forward with `if (logger.isDebugEnabled())`.

Thanks!

**Comment by antidata** [comment]
Forgot to mention that lazy evaluation is achieved using java 8 lambda expressions

**Comment by cogmission** [comment]
@antidata I'm sorry, I've been so swamped lately with work, I haven't gotten back to you on this. I have seen this and the documentation for the replacement string api both in Java7 and Java8 - and that's not really **my** issue with this.

My issue has to do with the creation of the String --> "closenessScores for expValues: {} and actValues: {} is: {}" - every time the call site is visited! This is expensive and useless in any other case than when tracing code. This is why I prefer the if statement, because HotSpot is smart enough to see that the branch is never visited (when trace is not enabled) and will simply remove the code during execution. This is something I learned during my stretch with the Orbitz spinoff G2SwitchWorks.

Does this make sense?

**Comment by antidata** [comment]
@cogmission I understand your concern about the creation of the String, using the lambda expression the creation/computing is deferred until needed, not sure how they are implemented but in the end I'm sure at least one object is created (the lambda exp).

I suggested that way to make the code less noise, but since we are not sure about the impact of the creation of lambdas I'm also OK to use `ifs`.

Will send and update soon. Thanks!

**Comment by cogmission** [comment]
@antidata Cool sounds good! :-)

I'm still not sure you understood me though. I understand that the "debug()" method or other relevant method internally defers the processing of the state to when the logger state is relevant - but what I'm saying is that the String itself when the line Logger.debug("xxx {} xxx") is reached - the string "xxx {} xxx" is **created**. I'm talking about the String even before the substitutions take place.

**Comment by cogmission** [comment]
Nice! :+1:

**Comment by antidata** [comment]
@cogmission Thanks, now we have defined this, will move forward and start with #209

**Comment by cogmission** [comment]
@antidata Great! Sounds good.



On Mon, May 4, 2015 at 9:16 PM, antidata <notifications@github.com> wrote:

> @cogmission <https://github.com/cogmission> Thanks, now we have defined
> this, will move forward and start with #209
> <https://github.com/numenta/htm.java/issues/209>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/htm.java/pull/219#issuecomment-98908227>.
>



-- 
*With kind regards,*

David Ray
Java Solutions Architect

*cortical.io <http://cortical.io/>*
Sponsor of:  HTM.java <https://github.com/numenta/htm.java>

d.ray@cortical.io
http://cortical.io

**Pull request merged**
