### PR TITLE
Synchronous compute

### LINKED ISSUE #260: HTM.java could use a synchronous "step" call that blocks until it returns an "Inference"
It isn't clear to me if it would be better to return the inference of the next predicted input, or if it would be better to return what the network predicted the current input would be.   Perhaps both?

### PR DESCRIPTION
**Pull request by cogmission**
Fixes #260 
Added ability to get returned Inference from a network compute call in a synchronous fashion (directly).

### CODE REVIEW

**Comment by cogmission** [comment]
@rhyolight Please accept

btw, is coveralls disabled?

**Comment by rhyolight** [comment]
Last build was 18 July... https://coveralls.io/github/numenta/htm.java

**Comment by rhyolight** [comment]
It is enabled, but I've been noticing some strange things happening with coveralls lately on other projects as well. Keep an eye out, we may need to figure out some other coverage reporting tool.

**Comment by rhyolight** [comment]
:+1:

**Comment by cogmission** [comment]
Hmm. There was a test failure in the downloaded log, and I believe the coveralls plugin was never run. The test failure is only local to Travis, as it was a test that hasn't changed in months, and runs fine locally on my machine.

The tests are run twice, once during the regular build and once to generate the instrumented classes for the coveralls plugin. The second one is the one that had the failure and not the first. I believe there may be a plugin problem since the coveralls plugin does some tampering with the binary code produced? (i.e. I have no clue).

I will keep an eye on it and investigate like you say.

**Pull request merged**
