### PR TITLE
Added Gradle wrapper

### LINKED ISSUE #454: Investigate adding GradleWrapper to build setup
Take a look at including Gradle Wrapper functionality to the build script.

### PR DESCRIPTION
**Pull request by calclavia**
Fixes #454 
Makes it easier to do Gradle install.

### CODE REVIEW

**Comment by cogmission** [comment]
@calclavia I added a reference to #454. Please let me know by end of day today if you would like to finish this contribution? You will need to sign the [Contributor's License](http://numenta.org/licenses/cl/) if you do...? Please let me know?

**Comment by calclavia** [comment]
@cogmission I signed the CL.

**Comment by rhyolight** [comment]
> I signed the CL.

@calclavia You should be good to contribute, thanks.

**Comment by calclavia** [comment]
To fix the build, will need someone with a unix system to perform chmod on the gradlew file so it can be executed on Travis.

**Comment by cogmission** [comment]
@calclavia Can you give me push privileges on your repo? I chmodded the gradlew file and want to push it to your repo. Also can you then create a branch and put your changes on that branch and resubmit your PR? We never merge directly from master?

**Comment by calclavia** [comment]
@cogmission Done

**Comment by cogmission** [comment]
@calclavia Nicely done! Thank you! 👍

**Pull request merged**
