### PR TITLE
Add a  low memory and fast implementation for input connections matrix.

### LINKED ISSUE #355: Add a fast and low memory implementation of SBM for input connection matrix
Low memory sparse binary matrix is too slow for  `Connections#connectedMatrix` due the  getSlice operations.

### PR DESCRIPTION
**Pull request by chelu**
- Add FastConnectionsMatrix for input connections (sparse).
- Remove sparse map from SparseBinaryMatrixSupport.
- Remove sparse map usage from SparseBinaryMatrix.

Fix #355

### CODE REVIEW

**Comment by cogmission** [comment]
@chelu Let me know when you have Coveralls happy?

Also, is there a test for this: https://github.com/chelu/htm.java/blob/ad9fcee11560e5d2ab0df8e585e72a5e814f78a1/src/main/java/org/numenta/nupic/util/SparseBinaryMatrixSupport.java#L76  ??

**Comment by chelu** [comment]
@cogmission Not, I'm not using this now. I write this method to provide a faster way to get the true counts in sparse form. However, as soon as I found out that the true counts are not used at all, I guess that I should not update thems in every set call.

**Comment by chelu** [comment]
However, I need to use it in clearStatistics default implementation...  I fix it

**Comment by cogmission** [comment]
@chelu :+1:

**Comment by cogmission** [comment]
@chelu Thank very much for your work! Is there something I can run to demonstrate the increase in speed? How did you compare?

**Comment by cogmission** [comment]
@chelu - I'm back from the Hackathon, are you around to discuss this so we can get this merged?

**Comment by cogmission** [comment]
@chelu I'm merging this because I now realize it was additive and doesn't substitute any code.

**Pull request merged**
