### PR TITLE
Create new Matrix hirearchy. 

### LINKED ISSUE #328: Create a low memory implementation of SparseBinaryMatrix
Exposing an image of 128x128 pixels,  8bits, grayscale to a network results in a memory usage of 16 GBytes for the backing array of `SparseBinaryMatrix`.

I proposal to add a new implementation without the backing array and a new `FlatMatrix` that use a `BitSet` for storing binary data.

### PR DESCRIPTION
**Pull request by chelu**
Create new Matrix hirearchy to allow implementations of FlatMatrix and low memory usage of SparseBinaryMatrix.

Fix #328

### CODE REVIEW

**Comment by cogmission** [comment]
@chelu Thanks for adhering to the dev process. Just making sure you see that you need to add tests?

**Comment by chelu** [comment]
OK, thanks @cogmission

**Comment by cogmission** [comment]
@chelu Yep, so this is what I do too. I submit test cases until the build passes :-P

**Comment by cogmission** [comment]
@chelu Nice Work!

So can you please explain very briefly the current hierarchy you are proposing? What classes inherit from what and their individual purposes? Also, did you confirm the memory savings? How much memory were you able to save for your implementation?

I just would like to get an understanding of the code and the divisions of responsibility you're proposing...

Thanks,
David

**Comment by chelu** [comment]
Hi @cogmission, of course: 

- **Matrix**:  Minimal matrix data access interface
- **FlatMatrix**: Extends Matrix for flat index data access. Used to replace `SparseObjectMatrix` instances that are full indexed like column or pool matrix.  Use an array storage instead a map.
- **SparseBinaryMatrixSupport**:  Base class for `SparseBinaryMatrix` implementations.
- **LowMemorySparseBinaryMatrix**:  `SparseBinayMatrix` without a backing array.
- **BitSetMatrix**: a FlatMatrix that store 1/0 in a BitSet instead an integer array. 

For a network with a Layer with 512x512 columns with an input for every column, the `ConnectedMatrix` in `Connections` will request a backing array of **16 Gb**. So I think that having a SparseBinaryMatrix without the backing array  is useful.

Note that for actually use it, you need to override `SpatialPooler#initMatrices` method.

I will try to use `BitSetMatrix` as replacement of the integer arrays in the future but actually is unused.

Thanks for your support.  

Jose.

**Comment by cogmission** [comment]
Can you change this too? : https://github.com/numenta/htm.java/pull/329/files#diff-542653af02823fbd7e8d10d022c66e84L969

**Comment by cogmission** [comment]
So in your code are you subclassing the SpatialPooler in order to implement the different matrices? If so, are you running into any problems with the NAPI ?

**Comment by cogmission** [comment]
Another small "nit". Can you correct the spacing (to 4 spaces) with no tabs? If you are using Eclipse, you can go to Preferences > Java > Editors and setting indentation to spaces is somewhere there. Then in your edited files, click <control> <a> , <control> <i>  to re-indent, or in OSx click <command> <a>, <command> <i>.

**Comment by chelu** [comment]
Fixed, No, I haven't problems with NAPI.

**Comment by cogmission** [comment]
@chelu Awesome! :+1:

**Comment by cogmission** [comment]
@chelu Please keep me informed on your performance observations in gitter, ok?

**Pull request merged**
