### PR TITLE
Fixed not filled overlaps array in updateDutyCycles

### LINKED ISSUE #452: Using not filled overlaps array in updateDutyCycles
```
public void updateDutyCycles(Connections c, int[] overlaps, int[] activeColumns) {
        double[] overlapArray = new double[c.getNumColumns()];
        double[] activeArray = new double[c.getNumColumns()];
        ArrayUtils.greaterThanXThanSetToY(overlaps, 0, 1); // here the wrong array got changed
       
        ......
        c.setOverlapDutyCycles(
                updateDutyCyclesHelper(c, c.getOverlapDutyCycles(), overlapArray, period));
    }

```

### PR DESCRIPTION
**Pull request by vova616**
Fixes #452

### CODE REVIEW

**Comment by cogmission** [comment]
Hi @vova616,

We have some "checks" that submitted code must pass first. 2 of these need to be satisfied in your case, ok?
1. Please fill out the Contributor License here: http://numenta.org/licenses/cl/ 
2. Please add test to SpatialPoolerTest.java which exercise the code you wrote, and possibly you may have to add more tests to keep Coveralls happy. Coveralls is a test coverage analysis tool which guarantees that the coverage always increases and will fail the build if it decreases - theoretically always making sure the overall code quality improves. 

---
Regarding your changes, I would rather see a method added to ArrayUtils which for all indexes above zero in one array, you set the value in the second array to 1. If you need help coming up with a name for the method, than I can help with that?

**Comment by cogmission** [comment]
@vova616 Please let me know by end of day today whether you are still interested in finishing this up, otherwise I will complete the work. This is a significant find of yours, and I wanted to give you a chance to add your contribution - but we can't wait for too long? Let me know?

**Comment by vova616** [comment]
Sure, sorry for the long wait, will get it done today/tomorrow

**Comment by cogmission** [comment]
@vova Just a friendly reminder... Please don't forget the [Contributor's License](http://numenta.org/licenses/cl/)

**Comment by vova616** [comment]
It looks like Coveralls does not like me, how can I make him happy?

**Comment by cogmission** [comment]
@vova616

:-)

You will have to add tests until Coveralls stops complaining. What I do is look at the coveralls link, then find the class with the worst coverage and make tests for the uncovered methods. The differential is only fractions of a percent, so it probably won't take more than one or two tests. 😜

**Comment by cogmission** [comment]
@vova616 I took a look at your work... Nicely Done! Hopefully Coveralls will behave...

**Comment by cogmission** [comment]
@vova616 Great job... merging...

**Pull request merged**
