### PR TITLE
Adding logging to SparsePassThroughEncoder

### LINKED ISSUE #207: SparsePassThroughEncoder requires the introduction of Logging
Use the current logging library and method present in the ScalarEncoder as a "template" for the introduction of logging. This should include the corresponding unit test as well.

### PR DESCRIPTION
**Pull request by antidata**
Fixes #207

### CODE REVIEW

**Comment by cogmission** [comment]
@antidata 
Thank you for your contribution!

A few "nits". 

Java has horrid Object explosion when concatenating Strings (i.e. "Str" + "ing"), so I would recommend using the style of logging such as: 

```Java
LOG.trace("input: {}, val: {}, value: {}, output: {}",
+					input, val, value, Arrays.toString(output));
```
...instead of 
```Java
LOG.trace("input: " + input + ", val: " + val + ", value: " + value + ", output: " + Arrays.toString(output));
```
...using the "{}" as replacement markers...

Secondly, can you use 4 spaces (no tabs) for indentation?

Also, for long lines, I prefer wrapping the line with "stepped" indentation rather than a new line for every continuation like so...

```Java
LOGGER.trace("Building new SparsePassThroughEncoder instance, outputWidth:  {} {} {}" 
    outputWidth,  " outputBitsOnCount: ", outputBitsOnCount);
```

instead of:

```Java
LOGGER.trace("Building new SparsePassThroughEncoder instance, outputWidth: " +
+                outputWidth +
+                " outputBitsOnCount: " +
+                outputBitsOnCount);
```

**Comment by antidata** [comment]
@cogmission Thanks for the comments, will send a fix :+1:

**Comment by cogmission** [comment]
:+1: I accept this. I don't know what coveralls is talking about? @rhyolight is it possible to set a threshold for coveralls coverage decreases? Because the same code is being exercised as before, therefore coveralls is on crack! :-P

**Comment by cogmission** [comment]
@rhyolight Without some kind of threshold or range of tolerance, that coveralls validation is rather annoying :-) If it were more accurate, than I would be all for it...

**Comment by cogmission** [comment]
@rhyolight Without some kind of threshold or range of tolerance, that coveralls validation is rather annoying :-) If it were more accurate, than I would be all for it...

**Comment by antidata** [comment]
Cool, can you assign me the other issues related to logging? 

Also I think that multiple calls to Logger in the same place should be avoided, like [this](https://github.com/numenta/htm.java/blob/master/src/main/java/org/numenta/nupic/encoders/ScalarEncoder.java#L445):

`LOGGER.trace("");`
`LOGGER.trace("input: " + input);`
`LOGGER.trace("range: " + getMinVal() + " - " + getMaxVal());`
`LOGGER.trace("n:" + getN() + "w:" + getW() + "resolution:" + getResolution() +`
`				"radius:" + getRadius() + "periodic:" + isPeriodic());`
`LOGGER.trace("output: " + Arrays.toString(output));`
`LOGGER.trace("input desc: " + decode(output, ""));`

I'm proposing just one call and use a multi line string as parameter. @cogmission What do you think?

**Comment by cogmission** [comment]
@antidata I think we should wrap these lines in an "if(LOGGER.isTrace()) { ...execute log statements } or whatever the call is to see if that log level is enabled. That way you only incur the cost of the "if" test. (which would be optimized out at runtime by the hotspot compiler). So any place where there seems like a lot of processing (i.e. two or more log statements); should get the attention you were talking about? How does that sound?

**Comment by cogmission** [comment]
@rhyolight  @antidata Also, since we have this coveralls validation test which tests the ratio of new code added and existing lines of code to the amount of code covered by tests, If you see this validation error, try adding a test to a test file (any test file) to increase the coverage? I don't want to get in the habit of ignoring this validation - because overall I feel it is a good thing? 

Bottom line - pick a test, any test and add a test line to it - because coveralls detected new lines added without any new tests. It may not be accurate in this case, but let's just do what we can do make it happy ok? I appreciate it... Plus it will only benefit the code...

**Comment by cogmission** [comment]
I'm accepting this, because we need to fine tune whatever Coverall's problem is? :-P

**Comment by cogmission** [comment]
@antidata Thank you for your work! I'm sorry to put you through all the rigamarole but I can't figure out why Coveralls won't behave correctly? 

@rhyolight  any ideas?

**Comment by antidata** [comment]
Ok, I was looking for more methods to add unit tests to increase it, but not sure what's happening. Maybe we can ask to Coveralls guys for guidance?

Feel free to assign me the other tickets related to logging. I'll be working on it this week. Thanks!

**Pull request merged**
