### PR TITLE
Dependencies - conflict with Maven

### LINKED ISSUE #287: Project dependencies problem
Trying to compile using 0.6.0 fails with the following message:

```
Downloading: file://${project.basedir}/libs/cortical/cortical-fxwidgets/0.9/cortical-fxwidgets-0.9.pom
Downloading: file://${project.basedir}/libs/cortical/cortical-twitterutils/0.9/cortical-twitterutils-0.9.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by antidata**
* Removing local repo from pom.xml
* Removing cortical-fxwidgets from Dependencies
* Removing cortical-twitterutil from Dependencies

Fixes #287

### CODE REVIEW

**Comment by cogmission** [comment]
Wow, I forgot to do that. Thank you @antidata !! :-)

We have to do the same for the Gradle file too. I'll do that if you want?

:+1:

**Comment by cogmission** [comment]
@antidata Hey, If I don't hear back from you by this evening about whether you want to edit the Gradle file too, I'll go ahead and merge this; but I just wanted to know if you'd like to solve the problem in all places? (Especially since this isn't really a Maven project but a Gradle project) :-)

**Comment by cogmission** [comment]
Cool! Muchas Gracias! :-)

I responded to your inquiry re: bumping version to 0.6.1 - should I wait for you to include that also?

**Comment by antidata** [comment]
Done deal @cogmission

**Comment by cogmission** [comment]
Awesomeness! Merging! @rhyolight

**Comment by cogmission** [comment]
@antidata @rhyolight Ok, new build is queued up on Maven Central - should be available in a matter of hours...

**Pull request merged**
