### PR TITLE
RandomDistributedScalarEncoder implementation & tests

### LINKED ISSUE #85: htm.java needs a RandomDistributedScalarEncoder
This class and test should be created to follow the same idioms and structure as the Encoder.java and ScalarEncoder.java class. The CategoryEncoder, can be used as an example.

### PR DESCRIPTION
**Pull request by connollyst**
Fixes #85 

Hi all,

This is my first pull request so I thought I'd keep it simple. Here's the port of [``random_distributed_scalar.py``](https://github.com/numenta/nupic/blob/master/nupic/encoders/random_distributed_scalar.py) and [``random_distributed_scalar_test.py``](https://github.com/numenta/nupic/blob/master/tests/unit/nupic/encoders/random_distributed_scalar_test.py).

* I added a few novel tests, and the ported tests are line for line.
* I added some improvements to ``ArrayUtils.range`` and threw in some tests.
* I tried to stay very close to the Python implementation but the main difference is an internal ``BucketMap`` object which helps organize the code a bit. I have an idea to make it a bit more object oriented, but will leave it as it is for now to simplify the pull request.

**Important:** ``getBucketValues`` is _not_ implemented. I don't see an implementation in Python and am frankly a bit unsure about this function's role & implementation. We can discuss later.

Cheers,
Sean

### CODE REVIEW

**Comment by connollyst** [comment]
Not sure why it flags me as not having signed the CL, I did so today. Maybe there's a delay?

**Comment by rhyolight** [comment]
> Not sure why it flags me as not having signed the CL, I did so today. Maybe there's a delay?

It's a manual process. I'll take care of it tomorrow in the office.

**Comment by connollyst** [comment]
Gotcha, cheers.

**Comment by cogmission** [comment]
Sean,

Great job! Thanks for adjusting the ArrayUtils.range() method to more closely approximate what the Python/Numpy functionality is. 

getBucketValues() is an array the same length as the output encoding that has as its indexed values the input value. For instance, For the array { "EU", "US", "UK" }, if each one were being encoded into an output array of size 12, and w == 3 (the number of bits used to encode each), the getBucketValues() might return something like {"EU", "EU", "EU", "EU", "US", "US", "US", "US", "US", "UK", "UK", "UK", "UK"} and the output (result encoding) would be:
1.) {1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0} = "EU"
2.) {0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0} = "US"
3.) {0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1} = "UK"

Now that bad:  :-P
Please don't send code through your IDE's formatter, I can't accept the code until its format has been returned to the original. This speaks to specifically two types of changes that were made.

1. The tab should be indented to 4 spaces (not 8)
2. The javadoc comments should have their parameter values on the same line as their descriptions.
For example

@param   var    the variable
--not--
@param  var
            the variable

Please do not send my code through your formatter, I don't understand why peeps do this? And please do not put line breaks in places where I did not originally have them. This is probably a pain to undo, but no one asked you to reformat all the code. You'll probably have to checkout the original code then add your changes *without* reformatting the entire text.

Ok, so enough of that. Great job! and thank you for your hard work!

Cheers,
David

**Comment by connollyst** [comment]
Hey David,

Totally agreed; if there's a formatting standard then it'll be adhered to.

Can you provide a standard formatting configuration? I'm guessing by your comments that you're using Eclipse, can you export your formatter settings (``Preferences > Java > Code Style > Formatter > Edit > Export``) and send them to me? I use IntelliJ but its fully compatible for formatting.

In the long run, if you're enforcing a formatting standard, it'll probably be best to include this somewhere - either downloadable from the wiki or directly in version control.

Cheers,
-Sean

**Comment by cogmission** [comment]
Sean,

Bad news.

I see this had been assigned already to @anubhavchaturvedi. I remember there were two people I asked to work together because one person was kind of stuck and another wanted to work on it. I thought this was you and anubhav. Apparently, those were two other developers. I'm sorry to do this to you, and I'm sorry I didn't warn you when you indicated that you already worked on this, but we have assignments in order to avoid these situations. I will take a look at his work and if its up to standard, I will have to accept it. I do apologize.

**Comment by cogmission** [comment]
Please talk to @anubhavchaturvedi, I believe he is willing to collaborate because I know you have done some excellent work?

**Pull request closed without merging**
