### PR TITLE
fixed an error in SpatialPooler.java

### PR DESCRIPTION
**Pull request by pulinagrawal**
refer to commit message

### CODE REVIEW

**Comment by rhyolight** [comment]
@pulinagrawal Thanks for the contributution! Please sign our [contributor license](http://numenta.org/licenses/cl/) before @cogmission consider's your request.

**Comment by cogmission** [comment]
Hi @pulinagrawal and welcome!

After you sign the CL, I'd like to ask what you discovered by setting that variable to "final" ? I don't see an inherent problem without that setting because the variable is in scope for the closure its used in? (And it would have come out in tests if it weren't)

**Comment by pulinagrawal** [comment]
Hi David,

When I ran the HelloSP.java yesterday it gave me some sort of runtime
error, which I don't exactly remember. When I went to the line number,
eclipse was telling me to fix this error by making minActiveDutyCycles
final. I did that and the code ran fine. So, I just thought I will push it.

Today, it ran without fixing that error. Sorry to bother you with this.

I am trying to run htm.java on MNIST database. If you feel my project can
help yours in any way let me know.

Mat, I will do that. Thanks.

Pulin Agrawal
पुलिन अग्रवाल

**Comment by pulinagrawal** [comment]
Hi,

I got that error again when I ran it on an MNIST image. I suspect it
happens conditionally with certain inputs. Following was the error.

Exception in thread "main" java.lang.Error: Unresolved compilation problem:
Cannot refer to the non-final local variable minActiveDutyCycles defined in
an enclosing scope

at org.numenta.nupic.research.SpatialPooler$3.eval(SpatialPooler.java:974)
at org.numenta.nupic.util.ArrayUtils.where(ArrayUtils.java:1215)
at
org.numenta.nupic.research.SpatialPooler.updateBoostFactors(SpatialPooler.java:972)
at org.numenta.nupic.research.SpatialPooler.compute(SpatialPooler.java:187)
at org.numenta.nupic.examples.sp.RunMNIST.run(RunMNIST.java:142)
at org.numenta.nupic.examples.sp.RunMNIST.main(RunMNIST.java:177)


Pulin Agrawal
पुलिन अग्रवाल

**Comment by cogmission** [comment]
Hi @pulinagrawal - Are you using JDK 8 ? or what version? Also, what happens when you run "gradle -Pskipbench check" from inside the repo dir on your computer?

**Comment by pulinagrawal** [comment]
I am using jdk & jre 7.
I don't have gradle on this machine. Will try it on my linux machine and let you know.

I am using Eclipse on Windows with Git Bash for git and other command line operations.

This is very weird. When I am running HelloSP on master branch it is running fine but it seems it never gets into updateBoostFactors(), which is why there is no problem. When I run HelloSP from another one of my branches, with no difference at all in code except I just added another example file and a library (which should not conflict with HelloSP code), it is going into this function and causing that error to show up in the runtime as an exception. Also both these branches have no differences with numenta's htm.java master.

If it is not causing you any problem we can close this issue. It might be something on my side.

**Comment by cogmission** [comment]
@pulinagrawal - The problem is that the minimum JDK version is set to the projects original goal which is JDK 8. It was always the intention to have that as the min version because this is a "newer" project and we didn't want to start out by being bogged down by legacy code. 

For all those who read this and want to still use JDK 7 and below you can compile with [Retrolambda](https://github.com/orfjackal/retrolambda) which will create a build capable of running on lesser versions.

I will add a note specifying this to the project's home page for clarification.

**Reason:** - JDK 7 may require more explicit scoping (setting variable outside of a closure to **final**).

**Pull request closed without merging**
