### PR TITLE
DateEncoder and test

### LINKED ISSUE #87: htm.java needs a DateEncoder
This class and test should be created to follow the same idioms and structure as the Encoder.java and ScalarEncoder.java class. The CategoryEncoder, can be used as an example.

### PR DESCRIPTION
**Pull request by utensil**
This is the PR of the work on and fixes #87 . It's ready to merge now.

During the implementation, I've noticed the new changes of `Encoder` and made use of:

* the builder pattern
* the elegant generic solution of the input type problem we'd discussed in #87

The `DateEncoder` involves multiple `ScalarEncoder`s , so I adapted some codes from `MultiEncoder`. In the meanwhile, `LogEncoder` and `CoordinateEncoder` were also helpful references.

Current progress(UPDATED):

* [x] The majority of the implementation in Python is ported
* [x] All tests were ported and passed
* [x] Fixes Issue Validator — This PR must be linked to an issue.
* [x] some abnormal branches are not ported yet, trying to figure out the corresponding logic in Java
* [x] deal with doubts marked as TODO
* [x] code clean up and style conformance 

The following would be handled as separate issues(marked as TODO in code, search the diff for more info):

* [ ] Improve the document of DateEncoder for both Python and Java version
* [ ] Because most of the ScalarEncoder fields have less than 21 bits(recommended in ScalarEncoder.checkReasonableSettings), so for now we set forced of DateEncoder to be true to override
* [ ] Encoder.getEncoderTuple() can return null, but logic in Encoder.addEncoder() expects at least one empty ArrayList<EncoderTuple>, so we need to prepare an initial EncoderTuple
* [ ] The logic of holidayEncoder when the date is before holiday is not the same as when after, why? And why no break?
* [ ] For the datetime encoder, the scalar value is not the number of seconds since epoch.
* [ ] Current implementation of DateEncoder throws at invalid Date, but testMissingValues in Python expects it to encode it as all-zero bits
* [ ] Why can getBucketValues return null for some encoders, e.g. MultiEncoder

### CODE REVIEW

**Comment by utensil** [comment]
image

I don't understand why. I've added the "fix" word in the main thread.

**Comment by utensil** [comment]
Great! All tests were ported and passed. Just needs to do code improvements and clean up. @cogmission You may start the code review if you have time. The earlier to raise style or API design issues, the better. :wink:

**Comment by cogmission** [comment]
@utensil Hey!

Sorry I've been away for a bit, but I just wanted to say things look good so far. I looked over the DateEncoder and its corresponding test and the code (and style) look good. Anything I would point out at this time would be splitting hairs (we all have our little quirks and preferences) - so onward ho!

**Comment by utensil** [comment]
@cogmission Thanks, I'm working on the remaining todos locally, and hopefully will have them complete soon.

@rhyolight Can you help with the Fixes Issue Validator?

**Comment by rhyolight** [comment]
> @rhyolight Can you help with the Fixes Issue Validator?

Yes. :wink:

**Comment by cogmission** [comment]
I'm curious. How do we comply with the validation?

On Wed, Jan 14, 2015 at 1:34 PM, Matthew Taylor <notifications@github.com>
wrote:

> @rhyolight <https://github.com/rhyolight> Can you help with the Fixes
> Issue Validator?
>
> Yes. [image: :wink:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/htm.java/pull/141#issuecomment-69976658>.
>



-- 
*We find it hard to hear what another is saying because of how loudly "who
one is", speaks...*

**Comment by rhyolight** [comment]
> @rhyolight Can you help with the Fixes Issue Validator?

Yes. :wink:

**Comment by rhyolight** [comment]
> @rhyolight Can you help with the Fixes Issue Validator?

Yes. :wink:

**Comment by rhyolight** [comment]
> I'm curious. How do we comply with the validation?

You must have `fixes #XXX` in the PR description, where XXX can be an issue number or a URL to the issue.

**Comment by cogmission** [comment]
That's what I thought, but look at Utensil's first line in the comment box? (This is the PR of the work on and fixes #87...) <-- do you mean it must be in the title?

**Comment by rhyolight** [comment]
No, not the title, the description (which shows up in the GitHub UI like
the first comment). I fixed the description by changing "fix #87" to "fixes
#87".

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by cogmission** [comment]
fix"es" I see cool :O)

**Comment by utensil** [comment]
Oh...But according to:

* https://github.com/blog/1506-closing-issues-via-pull-requests
* https://help.github.com/articles/closing-issues-via-commit-messages/

The following keywords will close an issue :

* close
* closes
* closed
* fix
* fixes
* fixed
* resolve
* resolves
* resolved

I just thought the same rule apply here. @rhyolight

**Comment by rhyolight** [comment]
@utensil thanks for pointing out: https://github.com/numenta/nupic.tools/issues/170

**Comment by cogmission** [comment]
@utensil, I just wanted to catch up with the current status on this. Was this completed, or are you still working on it? I'm not sure if I should merge this or not (I don't want to merge until you say its complete).

**Comment by utensil** [comment]
@cogmission The main part yes, but I still have some code clean up to complete, that requires some experimenting and it's not done and not pushed to Github. I hope to come up with most of them within the week.

**Comment by cogmission** [comment]
@utensil  Because you're operating off of an "ongoing" PR, I'm forced to keep bugging you to find out if this is considered "complete" or not? :)

**Comment by utensil** [comment]
@cogmission Sorry for the delay, this PR is now **finalized** with the latest push. :clap: :fireworks: 

You may now merge at will or do a final review. :smile: 

And I've updated the main thread with issues that can't be resolved within this PR (none are serious, but just requires some more discussion or work on the Python side) and would be handled as separate issues, here's a copy:

> * Improve the document of DateEncoder for both Python and Java version
> * Because most of the ScalarEncoder fields have less than 21 bits(recommended in ScalarEncoder.checkReasonableSettings), so for now we set forced of DateEncoder to be true to override
> * Encoder.getEncoderTuple() can return null, but logic in Encoder.addEncoder() expects at least one empty ArrayList, so we need to prepare an initial EncoderTuple
> * The logic of holidayEncoder when the date is before holiday is not the same as when after, why? And why no `break;`?
> * For the current implementation of DateEncoder, the scalar value is not the number of seconds since epoch.
> * Current implementation of DateEncoder throws at invalid Date, but testMissingValues in Python expects it to encode it as all-zero bits
> * Why can getBucketValues return null for some encoders, e.g. MultiEncoder

**Comment by cogmission** [comment]
@utensil Encoder.addEncoder (re: issue 3) should test the key returned from getEncoderTuple() and if it is null, an exception should be thrown to state that the "No Tuple containing parent 'parent.name' exists" - I'll fix this later. The code looks good. And we will have to follow up on the rest of these issues.

:+1:

**Pull request merged**
