### PR TITLE
Added Locale.US to MetricsTrace.java

### LINKED ISSUE #394: MetricsTraceTest.java failes due to JVM using local decimal punctuation
Here in Norway (entire Europe I guess), the JVM seems to prefer to use commas for decimal punctuation as opposed to dots (4,5 instead of 4.5), which causes the aforementioned test to fail when it's expecting results using dots. I tried to do a pull request just earlier, but it seems the build crashed when I tried to submit my change (and I wasn't a member yet)
public String prettyPrintDatum(Metric datum) {
        return String.format(Locale.US, "min: %.2f, max: %.2f, sum: %.2f, mean: %.2f, std dev: %.2f", 
            datum.min, datum.max, datum.sum, datum.mean, datum.standardDeviation);
 }
In addition, the build seemed to complain a lot about gradle failing. Personally, I've had to install gradle 2.10 to make shadowjar work.

### PR DESCRIPTION
**Pull request by Setus**
Fixes #394
Added Locale.US to ensure that the tests were executed using dot decimal punctuation only.

### CODE REVIEW

**Comment by Setus** [comment]
Seems like I still haven't got my CL approved. 
Travis seems to be perpetually building, or not at all since I get the message "Hang tight, the log cannot be shown until the build has started." when I clik on Details.

**Comment by Setus** [comment]
Woohoo! Travis managed to build successfully, just the CL approval remaining then.

**Comment by rhyolight** [comment]
@Setus We processed the license... something is wrong with the validator. I think it is just a case-sensitivity issue. @cogmission you are good to merge despite the failing "Contributor Validator". I'm working on that.

**Comment by rhyolight** [comment]
Ok I guess I fixed it. ;)

**Comment by cogmission** [comment]
Good work @Setus and @rhyolight !

**Comment by Setus** [comment]
@cogmission Don't sweat it, it's been a fun learning experience, and thanks for putting up with me :smile:

**Pull request merged**
