### PR TITLE
Fixed documentation typo in CLA Classifier

### LINKED ISSUE #505: Documentation for CLA Classifier has typos regarding return types and decimal places
The documentation for the `compute` function incorrectly lists the return type as `dict` and the output example uses mixed decimal points (comma and full stop).

### PR DESCRIPTION
**Pull request by JonnoFTW**
Fixes #505 

I fixed a typo about the return type and the example in the comment using mixed decimal point styles.

### CODE REVIEW

**Comment by cogmission** [comment]
@JonnoFTW 

Also, you need to sign the CL ([contributor's license](http://numenta.org/licenses/cl/)) and then Matt will "approve" it and that first error will go away ;-)

You need to open up an "issue" and then in the comment above within this PR, you should put ```Fixes #<issue num>" --> take [a look at this as an example](https://github.com/numenta/htm.java/pull/503) (where it says "Fixes") at the top.

**Comment by cogmission** [comment]
@rhyolight Please review @JonnoFTW 's CL

**Comment by cogmission** [comment]
@JonnoFTW Have you signed the Contributor's License yet?

**Comment by JonnoFTW** [comment]
@cogmission yes I have. I got confirmation that it was received this morning.

**Comment by rhyolight** [comment]
@JonnoFTW @cogmission It's all good. There is something wrong with the validator. Good to merge. 👍

**Comment by cogmission** [comment]
@rhyolight Thanks buddy!

**Pull request merged**
