### PR TITLE
Update pom.xml to add systemPath for algorithmfoundry-shade-culled

### LINKED ISSUE #555: maven build fails because of missing dependency
**DESCRIPTION**

Maven build of htm.java  fails saying 'algorithmfoundry:algorithmfoundry-shade-culled:jar:1.3' is missing.

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.705 s
[INFO] Finished at: 2021-10-22T21:44:52+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project htm.java: Could not resolve dependencies for project org.numenta:htm.java:jar:0.6.13: Could not find artifact algorithmfoundry:algorithmfoundry-shade-culled:jar:1.3 in repo (http://metaware.us/maven3) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**REPRODUCE PROCEDURE**

Just try to clone & buid htm.java using maven.

In case of me, build environment is the following:
* OS : Ubuntu 20.04 LTS w/llinux-image-5.4.0-40-generic
* Java: 11.0.11+9-0ubuntu2~20.04 (ubuntu bundled) 
* Maven: 3.6.3-1 (ubuntu bundled) 
* htm.java version 
   * HEAD of master with commit timestamp "Wed Sep 15 21:44:59 2021 -0500"
```
$ git log -n 1 --oneline
886f7cf8 (HEAD -> master, origin/master, origin/HEAD) Updated to test permissions
```

**ANALYSYS and SUGGESTED RESOLUTION**

It seems this is a long standing(?) issue as you can find out below:

https://discourse.numenta.org/t/dependency-problem-from-maven-release/2042

The original Matrix Tool Kit for Java implementation (with a method addRow() that missing in the current MTJ) from algorithmfoundry seems to have been lost, and now htm.java bundles a copy of 'algorithmfoundry-shade-culled-1.3.jar' under 'libs' directory.

Thus, just updating pom.xml like below resolves this issue.

```
$ diff -u  pom.xml pom.xml.new
--- pom.xml     2021-10-23 09:11:55.324013034 +0900
+++ pom.xml.new 2021-10-22 21:30:08.009629309 +0900
@@ -144,6 +144,8 @@
                        <groupId>algorithmfoundry</groupId>
                        <artifactId>algorithmfoundry-shade-culled</artifactId>
                        <version>1.3</version>
+                       <scope>system</scope>
+                       <systemPath>${project.basedir}/libs/algorithmfoundry-shade-culled-1.3.jar</systemPath>
                </dependency>
        </dependencies>
```

I will create a PR for this soon.

Regards,
Masanori

### PR DESCRIPTION
**Pull request by thatsdone**
Update pom.xml to add systemPath for libs/algorithmfoundry-shade-culled-1.3.jar and resolve #555.

### CODE REVIEW

**Comment by cogmission** [comment]
Hi,

Thank you for your interest and contribution! I've been away for a long time! This repo should also have a reference to my server for network loading of the dependency? I have to check (this is just my seat-of-the-pants initial reaction). I'll get back to you! Thanks again! :)

**Comment by thatsdone** [comment]
Hi @cogmission,

I think now the repo has references to only oss.sonatype.org (in addition, thery are activeByDefault = false).

Regards,
Masanori

**Comment by cogmission** [comment]
'Hi,
Please take a look at this:
```
<repositories>
		<repository>
			<id>repo</id>
			<name>htm.java</name>
			<url>http://metaware.us/maven3</url>
		</repository>
	</repositories>
```

**Comment by thatsdone** [comment]
Hi @cogmission,

OK, but actually maven tries to lookup 'http://metaware.us', but the necessary files look like missing even there and unresolvable including other fallback repositories like below.


```
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------< org.numenta:htm.java >------------------------
[INFO] Building htm.java 0.6.13
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from repo: http://metaware.us/maven3/algorithmfoundry/algorithmfoundry-shade-culled/1.3/algorithmfoundry-shade-culled-1.3.pom
Downloading from central: https://repo.maven.apache.org/maven2/algorithmfoundry/algorithmfoundry-shade-culled/1.3/algorithmfoundry-shade-culled-1.3.pom
[WARNING] The POM for algorithmfoundry:algorithmfoundry-shade-culled:jar:1.3 is missing, no dependency information available
Downloading from repo: http://metaware.us/maven3/algorithmfoundry/algorithmfoundry-shade-culled/1.3/algorithmfoundry-shade-culled-1.3.jar
Downloading from central: https://repo.maven.apache.org/maven2/algorithmfoundry/algorithmfoundry-shade-culled/1.3/algorithmfoundry-shade-culled-1.3.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.619 s
[INFO] Finished at: 2021-10-24T08:56:16+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project htm.java: Could not resolve dependencies for project org.numenta:htm.java:jar:0.6.13: Could not find artifact algorithmfoundry:algorithmfoundry-shade-culled:jar:1.3 in repo (http://metaware.us/maven3) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

I also checked existence of the files using curl. At the redirected URL that 301 response says, tomcat returns 404.
```
$ curl http://metaware.us/maven3/algorithmfoundry/algorithmfoundry-shade-culled/1.3/algorithmfoundry-shade-culled-1.3.pom
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://www.metaware.us/maven3/algorithmfoundry/algorithmfoundry-shade-culled/1.3/algorithmfoundry-shade-culled-1.3.pom">here</a>.</p>
</body></html>
```

Regards,
Masanori

**Pull request closed without merging**
