### PR TITLE
#405 - reference build environment w/ docker

### LINKED ISSUE #405: Provide a docker-based standard build environment
As a convenience to developers, provide a Dockerfile that constructs a standard build environment for the **HTM.java** library.

The environment shall contain:
- OpenJDK 1.8.0_72
- Gradle 2.12
- Maven 3.3.9

### PR DESCRIPTION
**Pull request by EronWright**
Defines a 'reference' build environment that should 'always work'.  Based on the official OpenJDK8 docker image (Debian-based) plus Gradle 2.12.

Closes #405.

### CODE REVIEW

**Comment by cogmission** [comment]
Hi Eron,

This looks exciting!  Before we get started, the reason why you have "unsuccessful checks" is because you need to put "Fixes #nnn" in your first line of the first comment in this PR (It's a Numenta policy that all PRs address specific Issues) - and you need to create an "Issue" that explains what the "need" is, then reference it here in this PR as described above,

See these for an example of what I'm talking about: #399 , #400  see the comment in the last one.

:+1:

**Comment by cogmission** [comment]
Secondly, I wanted to ask if you could extend the wiki (add to the side bar on the right too)?

The side bar could be Docker File Setup, or Docker: Universal Working Reference Build Env or something probably shorter than that last suggestion :-P 

...and then create that wiki page explaining how to use your new environment? Or you can write the wiki text and I can put it in to the repos wiki structure if you like? I will help if needed?

Cheers, and **great work**,

David

**Comment by cogmission** [comment]
Also, the Docker version should use the Oracle JDK, at least I think so?

**Comment by cogmission** [comment]
@EronWright  I solved the Linux issue, its Gradle once again... You have to make sure that Gradle is pointing to the right version of Java...

**Comment by EronWright** [comment]
This weekend:
1. I'll move the README content to the wiki as you suggest.
2. I'll take a look at the test issues that are breaking the build under OpenJDK.
3. I'll file an issue.

**Comment by cogmission** [comment]
@EronWright Awesomeness! Thank you... :+1:

**Comment by cogmission** [comment]
@EronWright I didn't see the README.md changes... I think you should leave the section entitled:
```
**Reference Build Environment**
Follow the instructions [here](http://github.com... some wiki url) to create a Docker image containing an HTM.java build environment.

**Note:** This is _**only**_ necessary if you want to run HTM.java inside Docker. If you want a "normal" build environment, then you can skip these instructions.
```

**Comment by cogmission** [comment]
@EronWright Please look at my last Gitter comment, the versions while the same don't cause the issue. Gradle must point to **exactly the same JDK installation.** (at least that's what I have seen over and over again now, the latest being with @addos)

**Comment by EronWright** [comment]
Closes #405.

**Comment by EronWright** [comment]
@cogmission please review.   All tests pass with Gradle and with Maven.  Please consider #406 as a prerequisite.

Note that I moved some of the build instructions to a dedicated wiki page.

**Comment by cogmission** [comment]
Great! Thank you @EronWright :+1: 

I didn't see the " **_PA_**LayerTest in the error output so I thought my fix didn't work :-( " I thought the error was with "LayerTest" still, because it was the same three internal tests. Thank you for catching that! I should have added the fix to that test class too...

**Pull request merged**
