### PR TITLE
fixes #249:

### LINKED ISSUE #249: HTMSensor returns null instead of empty Optional
A short recipe for crashes due to cryptic NPE:

```java
Exception in thread "main" java.lang.NullPointerException
	at org.numenta.nupic.network.sensor.HTMSensor.makeIndexEncoderMap(HTMSensor.java:179)
	at org.numenta.nupic.network.sensor.HTMSensor.initEncoder(HTMSensor.java:539)
	at org.numenta.nupic.network.Network.setSensor(Network.java:455)
	at org.numenta.nupic.network.Region.setNetwork(Region.java:121)
	at org.numenta.nupic.network.Network.add(Network.java:395)
```

Other encoders have the same problem.

### PR DESCRIPTION
**Pull request by clumsy**
Fixes #249 
a check for not initialised encoders is more 
robust and verbose

### CODE REVIEW

**Comment by clumsy** [comment]
Hm, why isn't linked when there's 'fixes' keyword? The CLA was signed too...

**Comment by cogmission** [comment]
@clumsy @rhyolight I think that the ":" after the "fixes" keyword is not parsed right?

**Comment by cogmission** [comment]
The contributor license will be acknowledged probably tomorrow when @rhyolight gets back to work on Monday. Thanks @clumsy !

**Comment by clumsy** [comment]
OK I've updated the patch, should be fine now.

**Comment by cogmission** [comment]
@clumsy One more thing (nit sorry). Can you please keep the spaces around the "{" brackets and other spaces the same? I know it is really a "nit" but if you don't do it, then I have to, ok?

**Comment by cogmission** [comment]
@rhyolight I don't see @clumsy added to the "assignee" drop down list?

**Pull request merged**
