### PR TITLE
Reorder start() and subscribe() for possible thread race

### LINKED ISSUE #403: OpenJDK build tests fail
This issue is an attempt to fix htm.java on OpenJDK which produces some test failures...

### PR DESCRIPTION
**Pull request by cogmission**
Fixes #403 

Hopefully... I don't have OpenJDK, but I highly suspect the following changes will solve this.

### CODE REVIEW

**Comment by cogmission** [comment]
@rhyolight No new changes, no new code. Just reordered 2 statements in 4 or 5 tests is about all... So I want to merge this so that @EronWright can test this tomorrow.

**Comment by EronWright** [comment]
Would you mind trying the docker-based build PR?  It would be nice for someone to give it a try.

**Comment by cogmission** [comment]
@EronWright Ok, installed Docker, and went through their tutorial, installed your Dockerfile and tested this new code. (It didn't fix the problem)

So now I want to start eclipse from within a Docker image so I can run and debug using OpenJDK (isolated from the rest of my system and environment because I really don't have time to mess with that and finish Serialization)

Do you know how to setup Docker so I can run Eclipse from within that environment so I can solve this OpenJDK issue?

**Comment by cogmission** [comment]
@EronWright Your instructions were great! BTW I had no problem following along...

**Comment by cogmission** [comment]
I think I found a way to install Eclipse under docker... https://github.com/fgrehm/docker-eclipse

**Comment by EronWright** [comment]
An alternative is to use remote debugging, by running the container with `-p 5005:5005`, running gradle with the debugger on, and attaching to the address returned by `docker-machine ip default`.

I will do that later today, and update the doc with better instructions.

**Pull request merged**
