### PR TITLE
Fixes #522

### LINKED ISSUE #522: Test case failures under Windows
Issues reported here: https://discourse.numenta.org/t/gradle-build-failed/2724/3

Based on my execution results there are a couple of different non-critical causes.

The first is to do with how file deletions are handled by the JVM in Windows. The HTMNetworkTests directory is being deleted at the end of some tests and then created again by another test, but in reality the previous one hasn’t completed yet and there is still an open handle, this causes IOExceptions. You’ll notice that if you run the failed test(s) in isolation, they will pass.

The issue in testMain is that \n is used as a line separator when streaming out, then the test asserts that this resulted in a new line. Replacing “\n” with System.lineSeparator() is the cross platform fix, as it will retain “\n” in mac/linux and use “\r\n” in Windows.

### PR DESCRIPTION
**Pull request by jamesweakley**
Addresses the two identified causes of test case failures in Windows

### CODE REVIEW

**Comment by jamesweakley** [comment]
I've signed the license, does it take some time to come into effect?

**Comment by cogmission** [comment]
@rhyolight  (Matt) Has to approve it and do some administrative stuff...

Thanks James!

**Comment by rhyolight** [comment]
I think it is processed now...

**Comment by cogmission** [comment]
Looks good James, thanks!

**Pull request merged**
