### PR TITLE
Adding GeospatialCoordinateEncoder Builder configuration

### LINKED ISSUE #323: GeospatialCoordinateEncoder Builder configuration
HTMSensor.java needs to be able to load builder configuration for GeospatialCoordinateEncoder.

### PR DESCRIPTION
**Pull request by antidata**
Fixes #323

### CODE REVIEW

**Comment by cogmission** [comment]
@antidata  Nice job. Thank you for your hard work! Can you write a test in HTMSensorTest to show that this works?

**Comment by antidata** [comment]
@cogmission There is another issue (not sure if related to this,  but we need to fix it), see exception:

```
scala> publisher.onNext("7/2/10 0:00,21.2,40.6457;-73.7962")
java.lang.ClassCastException: [D cannot be cast to org.numenta.nupic.util.Tuple
at org.numenta.nupic.encoders.GeospatialCoordinateEncoder.encodeIntoArray(GeospatialCoordinateEncoder.java:27)
at org.numenta.nupic.encoders.MultiEncoder.encodeIntoArray(MultiEncoder.java:100)
at org.numenta.nupic.encoders.Encoder.encode(Encoder.java:622)
at org.numenta.nupic.network.sensor.HTMSensor.input(HTMSensor.java:390)
at org.numenta.nupic.network.sensor.HTMSensor.lambda$getOutputStream$4(HTMSensor.java:323)
at org.numenta.nupic.network.sensor.HTMSensor$$Lambda$28/767275708.apply(Unknown Source)
```

**Comment by cogmission** [comment]
Ok I'll take a look tomorrow.

**Comment by antidata** [comment]
Ok, some more code for you if you wanna reproduce (I'm using the scala console)

```java
public static Map<String, Map<String, Object>> getNetworkDemoFieldEncodingMap() {
        Map fieldEncodings = setupMap((Map)null, 0, 0, 0.0D, 0.0D, 0.0D, 0.0D, (Boolean)null, (Boolean)null, (Boolean)null, "timestamp", "datetime", "DateEncoder");
        fieldEncodings = setupMap(fieldEncodings, 50, 21, 0.0D, 100.0D, 0.0D, 0.1D, (Boolean)null, Boolean.TRUE, (Boolean)null, "consumption", "float", "ScalarEncoder");
        fieldEncodings = setupMap(fieldEncodings, 999, 25, 0.0D, 100.0D, 0.0D, 0.1D, (Boolean)null, Boolean.TRUE, (Boolean)null, "location", "geo", "GeospatialCoordinateEncoder");
        ((Map)fieldEncodings.get("timestamp")).put(Parameters.KEY.DATEFIELD_TOFD.getFieldName(), new Tuple(new Object[]{Integer.valueOf(21), Double.valueOf(9.5D)}));
        ((Map)fieldEncodings.get("timestamp")).put(Parameters.KEY.DATEFIELD_PATTERN.getFieldName(), "MM/dd/YY HH:mm");
        ((Map)fieldEncodings.get("location")).put("timestep", "60");
        ((Map)fieldEncodings.get("location")).put("scale", "30");
        return fieldEncodings;
    }
```

```scala
val modelParameters = NetworkParameters.getModelParameters

val publisher = Publisher.builder.addHeader("timestamp,consumption,location").addHeader("datetime,float,geo").addHeader("T,,").build

val parms: SensorParams = SensorParams.create(Keys.obs.get(), "", publisher)

val sensor: Sensor[ObservableSensor[String]] = Sensor.create(HtmModelFactory.sensorFactory, parms)

val net = Network.create("Network API Demo", modelParameters)
      .add(Network.createRegion("Region 1")
      .add(Network.createLayer("Layer 2/3", modelParameters)
      .alterParameter(KEY.AUTO_CLASSIFY, true)
      .add(Anomaly.create)
      .add(new TemporalMemory)
      .add(new SpatialPooler)
      .add(sensor)))


net.observe().subscribe(new Subscriber[Inference]() {
            def onNext(i: Inference) {
		println(s"{i}")
            }
            override def onError(throwable: Throwable): Unit = {
              println(throwable.getMessage)
            }
            override def onCompleted(): Unit = {}
          })


```

**Comment by cogmission** [comment]
@antidata I need to push my changes to your repo - can you give me temporary permissions?

**Comment by antidata** [comment]
@cogmission Added

**Comment by cogmission** [comment]
:+1: Thank you @antidata

**Pull request merged**
