### PR TITLE
Cortical.io & Network API Demo (Now with GUI)

### LINKED ISSUE #245: Need to Create Cortical.io Demo
Create a demo to show the new Network API and new Cortical.io API capabilities...

### PR DESCRIPTION
**Pull request by cogmission**
Fixes #245 
All  functionality complete, still could use some more tests; and no GUI yet...

### CODE REVIEW

**Comment by cogmission** [comment]
Added demo test class and extensive tests. Re-worked Demo to make it entirely testable.

**Comment by cogmission** [comment]
Ok. Looks like overall test coverage decreased. Going to add some more tests to get this up...

**Comment by cogmission** [comment]
Finally! Test coverage increased! Please ok this one @rhyolight

**Comment by rhyolight** [comment]
:+1:

**Pull request merged**
