### PR TITLE
Quick test fix

### LINKED ISSUE #237: QuickTest: Doesn't allow for turning reset off
We need to watch this: #232 to make sure this isn't a bug in the CLAClassifier - but for now it just looks like a bug in QuickTest.java

The issue: learnIteration - nSteps was returning -1 resulting in pattern history queue misses for the sequence start.

Fix is to stop recycling the recordNum (allow it to keep incrementing) because we're not resetting so all records are new even though the data recycles. This allows the learned transition of "end-of-week" --> "beginning-of-week" to be properly stored in the deque.

### PR DESCRIPTION
**Pull request by cogmission**
Fixes #237 #232

### CODE REVIEW

**Comment by cogmission** [comment]
@rhyolight Please review. This is just a simple change to the QuickTest demo file...

**Comment by chessweb01** [comment]
Line 205 should be `switch((sequenceNum + 1) % 7) {` instead of `switch(recordNum) {`. Otherwise the output doesn't show the days once `recordNum` gets larger than `7`.

**Comment by chessweb01** [comment]
Line 205: `switch(value.intValue())`instead of `switch(recordNum)`. Otherwise the days are missing once recordNum exceeds `7`.

**Comment by cogmission** [comment]
@chessweb01 Thanks, also made the same change to Line 211 and well as Line 201.

**Comment by chessweb01** [comment]
I still think there is a problem with the classification itself. In case `isResetting == true`, `CLAClassifier 1 step prob[0]` never differs from zero for the same reason as before. It should be small, but not identical to zero.

**Comment by cogmission** [comment]
@chessweb01 After careful consideration, I see now that the code isn't necessarily incorrect. The understanding is that there really should never be a probability anticipated for record number "0". Which makes sense, because the system does not have any knowledge of anything occurring before time "t". The TemporalMemory is in alignment with this understanding because it never predicts anything either for a zero'th time step when coming from the last step in a previous sequence. Additionally, letting the code go "out of range" for "learningIteration - nSteps = -1" prevents any further processing of each bit of an input vector, so it turns out to be more efficient too.

**I will however enquire about this to be absolutely certain:**

@rhyolight Can you have @scottpurdy or @subutai confirm that this assumption is ok?

The issue is: 

For cyclical data, and when resetting the TM (and therefore starting the recordNum back at 0 for every cycle) - Line 474 of CLAClassifier.py "if iteration == self._learnIteration - nSteps:" 
(where iteration = 0, self._learnIteration = 0, nSteps = 1)

results in the comparison: 0 == -1 --> false. 

This occurs for every cycle when the recordNum == 0.

When this happens, the code never searches or records an active bit history for that record and the resultant probability for bucket "0" always equals "0.0". Which conceptually is correct, however @chessweb01 believes that while the probability will always "fail" for bucket zero predictions with cyclical data, it should always have a history for that bucket?

**Comment by scottpurdy** [comment]
@cogmission - I am having trouble seeing what the issue is. The proposed change does not seem correct to me since it would learn on the wrong number of steps:

```
if iteration == self._learnIteration - nSteps or self._learnIteration - nSteps < 0:
```

**Comment by cogmission** [comment]
@scottpurdy You have to trace the code. Start at Line 474, imagine that you are getting record 0; see that "iteration" is 0 but the thing its being compared to is "-1"; see that you don't ever go into the next loop for record "0", and so never retrieve a history for record 0. 

You have to walk the code, otherwise you won't understand?

**Comment by scottpurdy** [comment]
Ok so you have record `0` at [line 474](https://github.com/numenta/nupic/blob/d0223e95b9e0764ecd36c98b67252c70e3da8571/nupic/algorithms/CLAClassifier.py#L474), the condition fails as expected and we skip the next loop. So we don't execute [the code highlighted here](https://github.com/numenta/nupic/blob/d0223e95b9e0764ecd36c98b67252c70e3da8571/nupic/algorithms/CLAClassifier.py#L480-L493). But that is correct behavior because the linked code is the learning phase, but there isn't anything for the classifier to learn yet. In order to learn, you need to map the bits at time `T` with the actual bucket/value at time `T+X`, where `X` is the number of prediction steps.

If we pass more data then at iteration `X`, line 474 will evaluate to true and the classifier learning will be done. We don't know the bucket/value until step `X` so it is impossible to learn until then.

**Comment by cogmission** [comment]
Understood. We still insert a list inside of the activeBithistory at the top of the method that is never used and makes it look like it should be. The code should probably handle zero case more explicitly so that it looks like the behavior is intended - otherwise we'll have to keep answering these questions and confuse our users just like we are now.

**Comment by scottpurdy** [comment]
> We still insert a list inside of the activeBithistory at the top of the method that is never used and makes it look like it should be.

Which line is that?

> The code should probably handle zero case more explicitly so that it looks like the behavior is intended - otherwise we'll have to keep answering these questions and confuse our users just like we are now.

I totally agree! That method could probably be split up as well to make reading and testing it easier.

**Comment by cogmission** [comment]
Sounds Good :-) At line 383. If you look up a few messages I talk about it just look for the words line 383

**Comment by scottpurdy** [comment]
Thanks for the pointer. We still need to add the pattern at line 383 since that keeps the history that we will associate with a bucket `X` steps in the future. I created an issue for cleaning up the compute method and documenting better - numenta/nupic#2222

**Comment by cogmission** [comment]
:+1

**Comment by cogmission** [comment]
@rhyolight I'm going to merge this since all my questions and concerns have been addressed and this represents the final form of the code prior to https://github.com/numenta/nupic/issues/2222 which is a related issue having to do with future refinements of the code but doesn't block this. I will adapt https://github.com/numenta/nupic/issues/2222 to htm.java at a later time.

**Pull request merged**
