### PR TITLE
Fixes for sonatype deployment

### LINKED ISSUE #230: HTM.java Sonatype Deployment Requires additional fixes
changes to build.gradle and pom.xml to satisfy Nexus staging rules and complete release was missing from issue #220

### PR DESCRIPTION
**Pull request by cogmission**
Fixes #230

### CODE REVIEW

**Comment by cogmission** [comment]
@rhyolight @subutai Success!!! Finally Numenta has a release version available to the public: http://repo1.maven.org/maven2/org/numenta/htm.java/0.5.0/

Oh my god what a pain!!!

So now I have a release setup on my home computer, but I would like to duplicate that process with you so I can tell you step by step how to set this up (having just gone through this - since you are on a mac) - Numenta should have access to this process...

**Comment by subutai** [comment]
> Success!!! Finally Numenta has a release version available to the public:

Great!  Congratulations!  It is a pain, but still a major milestone.

**Comment by rhyolight** [comment]
:+1:

**Comment by cogmission** [comment]
@subutai Thank you ;-)

**Pull request merged**
