### PR TITLE
Create new Matrix hirearchy.

### PR DESCRIPTION
**Pull request by chelu**
Create new Matrix hirearchy to allow implementations of FlatMatrix and low memory usage of SparseBinaryMatrix.

### CODE REVIEW

**Comment by cogmission** [comment]
@chelu Awesome! Thanks for your work!

@rhyolight Please provide @chelu with the github developer information so that he knows how to interact with our repository.

In summary: Jose, you first must fork the repo, then create a branch (don't work on master) and work from that. You then have to do a "fetch upstream master" then merge that upstream master into your local master. From there, you merge local master into your branch. This will avoid the above error which is about the "conflicts". Any PR that is submitted must be on a branch which we will then merge into master upon approval. 

To submit a PR, you must make sure that it is associated with an issue. If not, you must create an issue (all PRs must have a corresponding issue). Then in the PR description you must put the line:
```
Fixes #300
```
substituting "300" above with your issue number. This will get automatically picked up and satisfy one of the 3 checks we always do on new PRs. Also, when the PR gets merged, that statement allows the issues to be automatically closed.

Here's a link about handling the merge with a remote master (syncing a fork): https://help.github.com/articles/syncing-a-fork/

That will tell you what you need to know to handle keeping your fork updated so that you won't have conflicts. Additionally, @rhyolight  can send you the "Numenta" contribution procedure.

Thanks again for all of your nice work!

Cheers,
David

**Comment by cogmission** [comment]
@chelu Also, please sign the Contributor's License:

http://numenta.org/licenses/cl/

**Comment by cogmission** [comment]
@chelu After you sign the CL, @rhyolight will "approve" it and you will be added to the NuPIC developer's "Hall of Fame" :-)  ...and I will be able to assign this issue to you!

**Comment by chelu** [comment]
OK, already signed,  I will try again

**Comment by cogmission** [comment]
@chelu It may take a while for @rhyolight  (Matt) to respond because it is 4:00am in California where he is located :-P

**Comment by rhyolight** [comment]
@chelu See:

- https://github.com/numenta/nupic/wiki/Development-Process#3-do-the-work
- https://www.youtube.com/watch?v=Yc3PKaT1knU

**Pull request closed without merging**
