### PR TITLE
Fix computing flat index in SpatialPooler#getNeighborsND

### LINKED ISSUE #332: getNeighborsND uses wrong matrix for computing the flat index
Seems like SpatialPooler#getNeighborsND is using  InputMatrix to compute the flat index of a Memory Matrix:

I think that 
```java
  for(int i = 0;i < size;i++) {
            int flatIndex = c.getInputMatrix().computeIndex(neighborList.get(i), false);
            if(flatIndex == columnIndex) continue;
            neighbors.add(flatIndex);
        }
```

Should be

```java
 for(int i = 0;i < size;i++) {
            int flatIndex = topology.computeIndex(neighborList.get(i), false);
            if(flatIndex == columnIndex) continue;
            neighbors.add(flatIndex);
        }
```

### PR DESCRIPTION
**Pull request by chelu**
Fix #332

### CODE REVIEW

**Comment by cogmission** [comment]
@chelu I haven't scoured the code yet, but did changing this solve anything for you?

**Comment by chelu** [comment]
Yes,  I changed to fix an `ArrayIndexOutOfBoundsException`  when connecting `Layers` of different size.
The the method is called from `#inhibitColumnsLocal` with a memory memory matrix as topology, so computing the flat index on the inputMatrix is wrong.  It actually compute bad flat indexes unless input and memory have the same dimensions.

**Comment by cogmission** [comment]
Yes input and the memory must have the same **number** of dimensions, the actual dimensions don't have to be the same. I have to help my son w/homework I'll be back - but I've been over this, we can discuss this later...

**Comment by cogmission** [comment]
Now that I've thought about it, I was actually referring to another issue I've had which is alignment of input dimensions to column dimensions - which is a separate issue from this. I think you are probably right about the use of the column dimensions instead of the input dimensions. I think the method description in the python version confused me because it talks about "...reconstructing the topology of the  inputs"  see here: https://github.com/numenta/nupic/blob/master/src/nupic/research/spatial_pooler.py#L1576

Good catch. 
:+1:

**Pull request merged**
