### PR TITLE
From NuPIC: Can inhibitColumnsGlobal() execute without sort() ? #354 (#365) 

### LINKED ISSUE #354: From NuPIC: Can inhibitColumnsGlobal() execute without sort() ?
See: https://github.com/numenta/nupic/issues/2746 for explanation

Solved in Python version by:
https://github.com/numenta/nupic/pull/2747

See tests here for verification: https://github.com/numenta/nupic/blob/6363f21ab1fbf647dcc1c2b5d64a183389fcbac8/tests/unit/nupic/research/spatial_pooler_unit_test.py#L1275

### PR DESCRIPTION
**Pull request by smadasu**
Fixes #354 

Here I am using streams. This is not a replacement for nupic python argpartition function. I have measured the performance gain with this change. It gives atleast 4000% performance gain. Please review

### CODE REVIEW

**Comment by cogmission** [comment]
Hi @smadasu !

Sorry for the delayed response, I was away from my computer yesterday eve. I am anxious to see the difference!

The community has a contribution process which I can help you out with here. The 3 "x"'s above have to do with this process; and we must satisfy these measures before we can consider merging your contributions.

1. CL (Contributor's License) - Please fill out the form [at this link.](http://numenta.org/licenses/cl/) This will then be processed by Numenta (@rhyolight might not be able to get to this until Monday, so I appreciate your patience on this due to it being the weekend). But while you're waiting, you can... 

2. reference the "issue" your PR solves by editing your description above to include the words 
```
Fixes #354
```
on a separate line at the top... This will fix the 2nd issue entitled, "Fixes Issue Validator". All PR's in Numenta.org must be associated with an "Issue" for tracking.

3. We like for all code to be covered by tests or at least have the coverage remain constant or preferably increase. We enforce that with this 3rd requirement which does a scan of the ratio of tested lines of code to the total count of lines using the Coveralls tool. So we need you to add a test to your code in htm.java/src/test/java/org/numenta/nupic/algorithms/SpatialPoolerTest.java. 

Cheers @smadasu and thank you for your hard work!

David

**Comment by smadasu** [comment]
Hi David,
I have already submitted the CL yesterday. May be it will be cleared on Monday. I have updated PR description. As far as the code coverage, I have not added any new code. There was already a test covering the method I changed. Where I have taken out the need for ArrayUtils class, since it is not necessary. Which I think is the reason for code coverage going down

**Comment by cogmission** [comment]
Hi Sreenath,

Take a look at your comment now? ;-)  That is what I meant...

Re: [No new Code but Coveralls complains] - Sorry dude, we must make Coveralls Coverage stats always go up, so you will have to submit another test of something that is not already tested. I know its a pain but we _all_ have been through this! Lol! 

Try going to the coveralls website by clicking the "Details" link where the line "X coverage/coveralls - Coveralls decreased..." is. Then once there, navigate to the most "uncovered code and add some tests" (That will make it easy to do).

Cheers,
David

**Comment by smadasu** [comment]
Updated ArrayUtilsTest for code coverage

**Comment by cogmission** [comment]
Hi@smadasu,

 A couple of things while we wait for you CL. Can you make sure you are using spaces instead of tabs, and that the indent is set to 4 spaces instead of 8? Also, the title of this PR should keep the descriptive title, you only have to put "Fixes ###" in your comments not the title.

Once you fix the indentation and make sure you have no tabs, then everything else looks good :+1:

**Comment by smadasu** [comment]
Fixes #354. I have updated the spaces.

**Comment by cogmission** [comment]
@rhyolight please do not merge this. Just approve the CL. I need to vet the speed increase.

**Comment by rhyolight** [comment]
CL approved.

**Comment by cogmission** [comment]
Awesome thanks @rhyolight

**Comment by smadasu** [comment]
Hi @cogmission,
What is the update on this? ARe you able to test performance?
Thanks
Sreenath

**Comment by cogmission** [comment]
Hi @smadasu,

I will look at it today. I'm sorry I've been unusually swamped with work while at the same time under the weather due to weird sleep patterns. Usually this stuff has a much faster turn around... 

Cheers,
David

**Comment by cogmission** [comment]
Below you can see the **enormous** difference in performance. I omit 18 of 20 iterations for brevity's sake.

Before: (SP with Global Inhibition)
```
# Run progress: 30.00% complete, ETA 00:17:02
# Fork: 10 of 10
# Warmup Iteration   1: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
8.764 ms/op
# Warmup Iteration  19: 7.826 ms/op
# Warmup Iteration  20: 7.809 ms/op
Iteration  19: 7.760 ms/op
Iteration  20: 7.806 ms/op
```

With @smadasu 's fix: (SP with Global Inhibition)
```
# Run progress: 30.00% complete, ETA 00:17:03
# Fork: 10 of 10
# Warmup Iteration   1: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
5.033 ms/op
# Warmup Iteration  19: 3.795 ms/op
# Warmup Iteration  20: 3.789 ms/op
Iteration  19: 3.835 ms/op
Iteration  20: 3.834 ms/op
```

**Comment by cogmission** [comment]
Good work @smadasu !

**Comment by smadasu** [comment]
Fantastic @cogmission !!! I am glad that you could verify the performance boost. Thank you very much for your help. Looking forward to working with htm.java for many more fixes and enhancements. :thumbsup::smile:

**Comment by cogmission** [comment]
@smadasu Why the change? I'm just curious if there's something that you seen needs fixing that would help improve HTM.java? I'm open if you want to talk?

**Comment by smadasu** [comment]
Its just that by using JDK8 streams API, we can boost performance. Just wanted to show case it that's all :)

**Comment by cogmission** [comment]
@smadasu Can you email me?

**Comment by smadasu** [comment]
What do you want me to email about?

**Comment by cogmission** [comment]
@smadasu I was saying that so I could get _your_ email and write you about something...?

**Pull request merged**
