### PR TITLE
Fix configuration for JaCoCo

### LINKED ISSUE #266: Fix coverage report submission failure
Failure due to erroneous error during the "2nd build" for test coverage. Coveralls plugin instruments classes and something there is causing a test which passes the first pass of the build, to fail.

### PR DESCRIPTION
**Pull request by Godin**
Fixes #266 

In accordance with description of "prepare-agent" goal - see http://www.eclemma.org/jacoco/trunk/doc/prepare-agent-mojo.html

### CODE REVIEW

**Comment by cogmission** [comment]
@Godin Thank you for looking into this, 

I still get the following error:

[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Skipping htm.java
[INFO] This project has been banned from the build due to previous failures.
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.244 s
[INFO] Finished at: 2015-08-28T09:39:57-05:00
[INFO] Final Memory: 24M/958M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project htm.java: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/cogmission/git/htm.java && /Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/bin/java -javaagent:/Users/cogmission/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/cogmission/git/htm.java/target/jacoco.exec -Xmx2048m -Xms1024m -jar /Users/cogmission/git/htm.java/target/surefire/surefirebooter710147367167232406.jar /Users/cogmission/git/htm.java/target/surefire/surefire8958551388403083911tmp /Users/cogmission/git/htm.java/target/surefire/surefire_07031009613724672260tmp
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project htm.java: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /Users/cogmission/git/htm.java && /Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/bin/java -javaagent:/Users/cogmission/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/cogmission/git/htm.java/target/jacoco.exec -Xmx2048m -Xms1024m -jar /Users/cogmission/git/htm.java/target/surefire/surefirebooter710147367167232406.jar /Users/cogmission/git/htm.java/target/surefire/surefire8958551388403083911tmp /Users/cogmission/git/htm.java/target/surefire/surefire_07031009613724672260tmp
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /Users/cogmission/git/htm.java && /Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/bin/java -javaagent:/Users/cogmission/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/cogmission/git/htm.java/target/jacoco.exec -Xmx2048m -Xms1024m -jar /Users/cogmission/git/htm.java/target/surefire/surefirebooter710147367167232406.jar /Users/cogmission/git/htm.java/target/surefire/surefire8958551388403083911tmp /Users/cogmission/git/htm.java/target/surefire/surefire_07031009613724672260tmp
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.RuntimeException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /Users/cogmission/git/htm.java && /Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/bin/java -javaagent:/Users/cogmission/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/cogmission/git/htm.java/target/jacoco.exec -Xmx2048m -Xms1024m -jar /Users/cogmission/git/htm.java/target/surefire/surefirebooter710147367167232406.jar /Users/cogmission/git/htm.java/target/surefire/surefire8958551388403083911tmp /Users/cogmission/git/htm.java/target/surefire/surefire_07031009613724672260tmp
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:515)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:380)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:167)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:990)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:824)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:722)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by cogmission** [comment]
@Godin Hi, I am here if you require input from me to help with this...

**Comment by cogmission** [comment]
Which command did you run locally? I ran...
mvn -X clean install jacoco:report coveralls:report

I see on the PR that your change passed on the travis CI server - but I can't run the above command locally.

Are you running a different command to test this?

**Comment by Godin** [comment]
On my side ``mvn -V clean verify jacoco:report -Dmaven.test.redirectTestOutputToFile``:
```
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: /usr/local/Cellar/maven/3.3.3/libexec
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: /Users/evgeny.mandrikov/.java-select/versions/jdk8u45/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.4", arch: "x86_64", family: "mac"
16:54:54 [INFO] Scanning for projects...
16:54:54 [INFO]
16:54:54 [INFO] ------------------------------------------------------------------------
16:54:54 [INFO] Building htm.java 0.6.2
...
Tests run: 369, Failures: 0, Errors: 0, Skipped: 1

[INFO]
[INFO] --- maven-jar-plugin:2.3.2:jar (default-jar) @ htm.java ---
[INFO] Building jar: /private/tmp/htm.java/target/htm.java-0.6.2.jar
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:report (default-cli) @ htm.java ---
[INFO] Analyzed bundle 'htm.java' with 173 classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 38.617s
[INFO] Finished at: Fri Aug 28 16:53:26 CEST 2015
[INFO] Final Memory: 24M/280M
[INFO] ------------------------------------------------------------------------
```

Not sure that this is related to JaCoCo, and to investigate I need a way to reproduce this or more information, such as report about crash just above message ``VM crash``.

**Comment by cogmission** [comment]
@Godin 

I get this error when running your command:

```
Results :

Tests run: 49, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.305 s
[INFO] Finished at: 2015-08-28T10:20:38-05:00
[INFO] Final Memory: 24M/958M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project htm.java: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/cogmission/git/htm.java && /Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/bin/java -javaagent:/Users/cogmission/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/cogmission/git/htm.java/target/jacoco.exec -Xmx2048m -Xms1024m -jar /Users/cogmission/git/htm.java/target/surefire/surefirebooter4631401137393214298.jar /Users/cogmission/git/htm.java/target/surefire/surefire4397875889185177137tmp /Users/cogmission/git/htm.java/target/surefire/surefire_03113523713644658674tmp
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

Here's the entire output of command:  http://cogmission.ai/output.txt

mvn -X clean verify jacoco:report > output.txt

**Comment by cogmission** [comment]
@Godin I can provide links to output for any command you wish? Just let me know what command to run ?

**Comment by Godin** [comment]
@cogmission just above there is a line
```
# An error report file with more information is saved as:
# /Users/cogmission/git/htm.java/hs_err_pid1831.log
```
please share this file.

**Comment by cogmission** [comment]
@Godin Here it is:

http://www.cogmission.ai/hs_err_pid1831.log

**Comment by Godin** [comment]
@cogmission ok, I'm also able to reproduce this on my side. Seems like a JVM bug - https://bugs.openjdk.java.net/browse/JDK-8038985 ( same crash in the same place inside Troove library ) and seems that probability to face it increases after instrumentation of Troove by JaCoCo.

**Comment by cogmission** [comment]
Ok, so for now it appears that there is no resolution for this? btw, that link doesn't appear to be related to this issue, unless that is the underlying cause?

```
Bad graph detected in build_loop_late
```

I don't understand the relevance... but I'll take your word for it?

**Comment by Godin** [comment]
@codewatson I excluded Trove classes from instrumentation and seems that it helps.

**Comment by cogmission** [comment]
@Godin That is awesome! It works! Thank you!

**Comment by cogmission** [comment]
@Godin If you would like to participate as a contributor, you could receive credit for this fix and sign the Contributors License at: http://numenta.org/licenses/cl/

Otherwise I can submit your changes for you in a separate PR? Up to you....

**Comment by Godin** [comment]
For the record: JVM crash can be reproduced with ``mvn test -Dtest="*SpatialPoolerTest"``

**Comment by cogmission** [comment]
This happens only when the test is being instrumented? I wasn't sure what
the conclusion was that you came to?

Thanks,
David

On Mon, Aug 31, 2015 at 9:16 AM, Evgeny Mandrikov <notifications@github.com>
wrote:

> For the record: JVM crash can be reproduced with mvn test
> -Dtest="*SpatialPoolerTest"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/htm.java/pull/293#issuecomment-136383408>.
>



-- 
*With kind regards,*

David Ray
Java Solutions Architect

*Cortical.io <http://cortical.io/>*
Sponsor of:  HTM.java <https://github.com/numenta/htm.java>

d.ray@cortical.io
http://cortical.io

**Comment by Godin** [comment]
@cogmission IMO JaCoCo just increases probability of crash, making it easily observable in your tests when Trove4j classes instrumented and that's why I excluded them. I'm currently writing about this crash to Oracle.

**Comment by cogmission** [comment]
I see. Thank you for explaining. Please keep me in the loop if you hear
anything?  Afaik, there is no reason to instrument my support classes and
libraries anyway is there? The instrumentation as far as I understand it is
only to enable and determine test coverage - which I would think is only
necessary for my immediate codebase - I would think?

Thanks,
David

On Mon, Aug 31, 2015 at 9:56 AM, Evgeny Mandrikov <notifications@github.com>
wrote:

> @cogmission <https://github.com/cogmission> IMO JaCoCo just increases
> probability of crash, making it easily observable in your tests when
> Trove4j classes instrumented and that's why I excluded them. I'm currently
> writing about this crash to Oracle.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/htm.java/pull/293#issuecomment-136397313>.
>



-- 
*With kind regards,*

David Ray
Java Solutions Architect

*Cortical.io <http://cortical.io/>*
Sponsor of:  HTM.java <https://github.com/numenta/htm.java>

d.ray@cortical.io
http://cortical.io

**Comment by cogmission** [comment]
However it is interesting that the trove library presents these issues, and
its good that you are reporting this back to Oracle... ;-)

On Mon, Aug 31, 2015 at 10:06 AM, Evgeny Mandrikov <notifications@github.com
> wrote:

> @cogmission <https://github.com/cogmission> yes, there is no reason to
> instrument dependencies
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/htm.java/pull/293#issuecomment-136400323>.
>



-- 
*With kind regards,*

David Ray
Java Solutions Architect

*Cortical.io <http://cortical.io/>*
Sponsor of:  HTM.java <https://github.com/numenta/htm.java>

d.ray@cortical.io
http://cortical.io

**Comment by Godin** [comment]
Bug report: https://bugs.openjdk.java.net/browse/JDK-8134862

**Comment by cogmission** [comment]
@Godin Thank you. We'll continue to track the status of this also.

**Pull request closed without merging**
