### PR TITLE
Prep v0.6.3

### LINKED ISSUE #330: version 0.6.3 preparation
update the pom.xml and build.gradle files

### PR DESCRIPTION
**Pull request by cogmission**
Fixes #330

### CODE REVIEW

**Comment by cogmission** [comment]
@rhyolight Ramping up for new release... Please accept...

**Comment by cogmission** [comment]
@rhyolight Pause while we verify something for @antidata ...

**Comment by rhyolight** [comment]
ok lemme know

**Comment by antidata** [comment]
@cogmission Thanks for the update, it is working now :+1:

**Comment by cogmission** [comment]
@rhyolight Ok we're good to merge

**Pull request merged**
